Send maximum balance toggle with fixes for fee estimation
BreezeHub/BreezeProject pull request #95
Opened 2018-06-14 13:52 UTC by rjmacarthy

Send maximum balance toggle added to send modal. 

- Add toggle to send maximum available balance
- Logic to amend the fee estimation based on if maximum is selected and which fee is selected.

2018-06-16 00:37 UTC, fenix2222 requested changes

2018-06-16 00:37 UTC, fenix2222 commented on Breeze.UI/src/app/wallet/send/send.component.ts
> +    this.sendForm.controls['fee'].valueChanges.subscribe((value) => {
This subscription is never unsibscribed, potential memory leak. Please unsubscribe in `onDestroy`

2018-06-16 11:17 UTC, rjmacarthy commented
Review item addressed.

2018-06-18 11:57 UTC, fenix2222 approved these changes

2019-12-16 08:56 UTC, closed without merging